// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/jwks.json": {
            "get": {
                "description": "Returns the server's public RSA key in JWK format used to verify JWT signatures (RS256). Cacheable for 3600 seconds.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "JSON Web Key Set",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/.well-known/openid-configuration": {
            "get": {
                "description": "Returns the OpenID Provider Configuration Information as specified in OpenID Connect Discovery 1.0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "OIDC Discovery Document",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.OIDCDiscovery"
                        }
                    }
                }
            }
        },
        "/api/auth": {
            "get": {
                "description": "Returns the consent page context for the current authorization request, including the logged-in user ID, client ID, and requested scope. Requires an active user session.\nSubmits the user's consent decision (approve or deny) for the current authorization request. On approval, returns the stored ReturnURI (the original /oauth/authorize URL) so the frontend can redirect the browser. On denial, returns a redirect URI with error=access_denied.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "Auth"
                ],
                "summary": "Submit authorization decision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client identifier from the authorize request",
                        "name": "client_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Space-delimited scopes from the authorize request",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "description": "Authorization decision",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.AuthDecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.AuthDecisionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Returns the consent page context for the current authorization request, including the logged-in user ID, client ID, and requested scope. Requires an active user session.\nSubmits the user's consent decision (approve or deny) for the current authorization request. On approval, returns the stored ReturnURI (the original /oauth/authorize URL) so the frontend can redirect the browser. On denial, returns a redirect URI with error=access_denied.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "Auth"
                ],
                "summary": "Submit authorization decision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client identifier from the authorize request",
                        "name": "client_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Space-delimited scopes from the authorize request",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "description": "Authorization decision",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.AuthDecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.AuthDecisionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "get": {
                "description": "Returns whether the current session has an authenticated user. If logged in, also returns the redirect URI stored in the session.\nAuthenticates a user with username and password. Creates a server-side session and returns a redirect URI (either the stored ReturnURI from a prior authorize attempt, or /auth).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "Auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Returns whether the current session has an authenticated user. If logged in, also returns the redirect URI stored in the session.\nAuthenticates a user with username and password. Creates a server-side session and returns a redirect URI (either the stored ReturnURI from a prior authorize attempt, or /auth).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Auth",
                    "Auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/test": {
            "get": {
                "description": "Validates the Bearer access token from the Authorization header. Sets TokenInfo in the Gin context on success.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "API"
                ],
                "summary": "Bearer Token Verification Middleware",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token valid, TokenInfo set in context",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "description": "Ends the user session and redirects to the login page or the post_logout_redirect_uri.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "End Session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URI to redirect after logout",
                        "name": "post_logout_redirect_uri",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to login or post_logout_redirect_uri",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/oauth/authorize": {
            "get": {
                "description": "Authenticates the resource owner and issues an authorization code. Requires an active user session. Implicit and hybrid flows are removed per OAuth 2.1 security recommendations.",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "OAuth 2.0 / OIDC Authorization Endpoint",
                "parameters": [
                    {
                        "enum": [
                            "code"
                        ],
                        "type": "string",
                        "description": "Response type",
                        "name": "response_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client identifier",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI registered for the client",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space-delimited scopes (e.g. openid profile email)",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque value returned to the client",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nonce for ID token replay protection (recommended when scope includes openid)",
                        "name": "nonce",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PKCE code challenge",
                        "name": "code_challenge",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "S256"
                        ],
                        "type": "string",
                        "description": "PKCE method",
                        "name": "code_challenge_method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to redirect_uri with authorization code in query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Authenticates the resource owner and issues an authorization code. Requires an active user session. Implicit and hybrid flows are removed per OAuth 2.1 security recommendations.",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "OAuth 2.0 / OIDC Authorization Endpoint",
                "parameters": [
                    {
                        "enum": [
                            "code"
                        ],
                        "type": "string",
                        "description": "Response type",
                        "name": "response_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client identifier",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI registered for the client",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space-delimited scopes (e.g. openid profile email)",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Opaque value returned to the client",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nonce for ID token replay protection (recommended when scope includes openid)",
                        "name": "nonce",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PKCE code challenge",
                        "name": "code_challenge",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "S256"
                        ],
                        "type": "string",
                        "description": "PKCE method",
                        "name": "code_challenge_method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to redirect_uri with authorization code in query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/oauth/token": {
            "get": {
                "description": "Issues tokens based on the grant type. Supports authorization_code, password, client_credentials, and refresh_token grants. Returns id_token when scope includes openid and a user context exists. Client authentication via Authorization header (client_secret_basic) takes precedence over body params (client_secret_post) per RFC 6749 §2.3.1.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "OAuth 2.0 Token Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client credentials via HTTP Basic: Basic base64(client_id:client_secret)",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "authorization_code",
                            "password",
                            "client_credentials",
                            "refresh_token"
                        ],
                        "type": "string",
                        "description": "Grant type",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client identifier (required if not using Authorization header)",
                        "name": "client_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Client secret (required if not using Authorization header)",
                        "name": "client_secret",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Authorization code (authorization_code grant)",
                        "name": "code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI (authorization_code grant)",
                        "name": "redirect_uri",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Space-delimited scopes",
                        "name": "scope",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Username (password grant)",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Password (password grant)",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token (refresh_token grant)",
                        "name": "refresh_token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "PKCE code verifier",
                        "name": "code_verifier",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Issues tokens based on the grant type. Supports authorization_code, password, client_credentials, and refresh_token grants. Returns id_token when scope includes openid and a user context exists. Client authentication via Authorization header (client_secret_basic) takes precedence over body params (client_secret_post) per RFC 6749 §2.3.1.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2"
                ],
                "summary": "OAuth 2.0 Token Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client credentials via HTTP Basic: Basic base64(client_id:client_secret)",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "authorization_code",
                            "password",
                            "client_credentials",
                            "refresh_token"
                        ],
                        "type": "string",
                        "description": "Grant type",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client identifier (required if not using Authorization header)",
                        "name": "client_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Client secret (required if not using Authorization header)",
                        "name": "client_secret",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Authorization code (authorization_code grant)",
                        "name": "code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Redirect URI (authorization_code grant)",
                        "name": "redirect_uri",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Space-delimited scopes",
                        "name": "scope",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Username (password grant)",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Password (password grant)",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token (refresh_token grant)",
                        "name": "refresh_token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "PKCE code verifier",
                        "name": "code_verifier",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/userinfo": {
            "get": {
                "description": "Returns claims about the authenticated end-user. Requires a valid Bearer access token with openid scope.",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "OIDC UserInfo Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.UserInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Returns claims about the authenticated end-user. Requires a valid Bearer access token with openid scope.",
                "consumes": [
                    "application/json",
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OIDC"
                ],
                "summary": "OIDC UserInfo Endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.UserInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.AuthContextResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.AuthDecisionRequest": {
            "type": "object",
            "properties": {
                "authorize": {
                    "type": "boolean"
                },
                "deny": {
                    "type": "boolean"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.AuthDecisionResponse": {
            "type": "object",
            "properties": {
                "redirect": {
                    "type": "string"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_request"
                },
                "error_description": {
                    "type": "string",
                    "example": "The request is missing a required parameter."
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.LoginResponse": {
            "type": "object",
            "properties": {
                "redirect": {
                    "type": "string"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.LoginStatusResponse": {
            "type": "object",
            "properties": {
                "logged_in": {
                    "type": "boolean"
                },
                "redirect": {
                    "type": "string"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.OIDCDiscovery": {
            "type": "object",
            "properties": {
                "authorization_endpoint": {
                    "type": "string"
                },
                "claims_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code_challenge_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "grant_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id_token_signing_alg_values_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "issuer": {
                    "type": "string"
                },
                "jwks_uri": {
                    "type": "string"
                },
                "registration_endpoint": {
                    "type": "string"
                },
                "response_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scopes_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subject_types_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_endpoint": {
                    "type": "string"
                },
                "token_endpoint_auth_methods_supported": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userinfo_endpoint": {
                    "type": "string"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIs..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 7200
                },
                "id_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIs..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "ODk4YWY2Njkt..."
                },
                "scope": {
                    "type": "string",
                    "example": "openid profile"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "github_com_garfieldlw_OAuth-2_0-and-OpenID-Connect_internal_model.UserInfoResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@example.com"
                },
                "email_verified": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Admin User"
                },
                "sub": {
                    "type": "string",
                    "example": "1"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9096",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OAuth 2.0 + OpenID Connect Server",
	Description:      "Go implementation of OAuth 2.0 Authorization Server and OpenID Connect 1.0 Provider.\nSupports authorization code (with PKCE), password, client_credentials, and refresh_token grants per OAuth 2.1.\nImplicit and hybrid flows are removed per OAuth 2.1 security recommendations.\nIssues JWT access tokens and ID tokens signed with RS256. Provides JWKS and OIDC Discovery endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
